version: 2.

jobs:
  build_and_push:
    docker:
      - image: cimg/node:20.3.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Let's build and push image
          command: |
            version="build-$CIRCLE_BUILD_NUM"
            echo $version
            docker build -t zerah550/todo-app:$version .
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push zerah550/todo-app:$version

  Update_manifest:
    docker:
      - image: cimg/base:2023.06
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Updating Manifest file
          command: |
            TAG=$CIRCLE_BUILD_NUM
            ((TAG--))
            git clone https://github.com/qwe324fsf1324ffjgi/kube_manifest.git
            git config --global user.email "zerahabba1@gmail.com"
            git config --global user.name "Zerah"
            cd kube_manifest
            git checkout main || git checkout -b main
            git pull origin main
            echo "Updating to tag: build-$TAG"
            sed -i "s/build-.*/build-$TAG/g" manifest/deployment.yaml
            cat manifest/deployment.yaml

            # Skip if no changes were made
            git diff --quiet && echo "No changes to commit. Skipping push." && exit 0

            git add .
            git commit -m "new build with imgTag build-$TAG"
            git config credential.helper 'cache --timeout=600'

            # Push without timeout
            git push https://$GITHUB_PERSONAL_TOKEN@github.com/qwe324fsf1324ffjgi/kube_manifest.git main

workflows:
  GitOpsflow:
    jobs:
      - build_and_push
      - Update_manifest:
          requires:
            - build_and_push
